apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorsample
  labels:
    app: techtalk-lunch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: blazorsample
  template:
    metadata:
      labels:
        app: techtalk-lunch
        service: blazorsample
    spec:
      containers:
        - name: blazorsample
          image: acreuwakstechtalk.azurecr.io/blazorsample:62 # switch between 62 and 71
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              protocol: TCP