apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorsample
  labels:
    app: techtalk-lunch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: blazorsample
  template:
    metadata:
      labels:
        app: techtalk-lunch
        service: blazorsample
    spec:
      containers:
        - name: blazorsample
          image: acreuwakstechtalk.azurecr.io/blazorsample:67
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blazorsample
  labels:
    app: techtalk-lunch
    service: blazorsample
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: blazorsample
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: techtalk
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: <gitops.techtalk.io>
  - http:
      paths:
      - backend:
          serviceName: blazorsample
          servicePort: 80