trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c715335b-8e35-4502-9701-fe1c16667cc6'
  imageRepository: 'blazorsample'
  containerRegistry: 'acreuwakstechtalk.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/sample-app/BlazorSample/Server/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        buildContext: 'sample-app/BlazorSample/'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy to Kubernetes
  jobs:
  - job: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:   
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'akstechtalk'
        namespace: 'techtalk'
        manifests: '**/*.yml'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'