apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podsample
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: gitops-dev
  url: https://github.com/joostwent/clusters/aks/gitopsdemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: gitopsdemo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP